# Generated by Django 3.0.5 on 2020-04-04 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('caller', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calls.Callee')),
            ],
        ),
    ]
