# Generated by Django 3.0.5 on 2020-04-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20200404_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='callee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Callee'),
        ),
    ]
